source 'https://rubygems.org'

# Gems actually used by the scraper (scrape.rb + lib/)
gem 'addressable'
gem 'base64'
gem 'brotli'
gem 'certifi'
gem 'concurrent-ruby'
gem 'domain_name'
gem 'http-cookie'
gem 'http-form_data'
gem 'http_parser.rb'
gem 'httparty'
gem 'mechanize'
gem 'mime-types'
gem 'mime-types-data'
gem 'mini_mime'
gem 'multi_xml'
gem 'net-http-digest_auth'
gem 'net-http-persistent'
gem 'nokogiri'
gem 'playwright-ruby-client'
gem 'public_suffix'
gem 'rubyntlm'
gem 'rubyzip'
gem 'sqlite3'
gem 'webrobots'
gem 'write_xlsx'
